# CircleCI 2.1 configuration file with Bun.sh

defaults: &defaults
  docker:
    # Choose the version of Node you want here
    - image: cimg/base:current
  working_directory: ~/repo

version: 2.1
jobs:
  tests:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install bun
          command: curl -fsSL https://bun.sh/install | bash
      - run:
          name: Link bun
          command: alias bun="~/.bun/bin/bun"
      - run:
          name: Bundle with bun
          command: bun install
      - run:
          name: Run tests
          command: bun test

  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install bun
          command: curl -fsSL https://bun.sh/install | bash
      - run:
          name: Bundle with bun
          command: bun install
      - run:
          name: Connecting to NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish to NPM
          command: bun run ci:publish

workflows:
  version: 2.1
  test_and_release:
    jobs:
      - tests
      - publish:
          requires:
            - tests
          filters:
            branches:
              only: main
